### ISSUE TITLE
On_connection_close event does not get fired

### ISSUE THREAD

**Issue by aia** [zk-ruby/zk-eventmachine#1]
Want to thank you first for all the work on Ruby Zookeeper, Jonathan!
zk-eventmachine has been working great for me except for the following:

I want my program to receive a notification when a zookeeper server disconnects.
I am overwriting the on_connection_lost method in the following way:

``` ruby
require 'zk-eventmachine'
require 'pp'

Zookeeper.set_debug_level(4)

@zkem = ZK::ZKEventMachine::Client.new("127.0.0.1:2181")

@zkem.on_connection_lost do |event|
  pp ["==== zookeeper disconnected"]
end

EM.run {
  @zkem.connect do
    puts
    pp ["connected"]
  end
}
```

However, the on_connection_lost event never gets fired even though the events from C library pass by :(

``` ruby


["connected"]
DEBUG 0x101768000:zookeeper_lib.c:375: ZOOKEEPER_C_STATE WATCHER type = -1, state = 3, path = 0x7fb25a25a290, value = 

DEBUG 0x101662000:zookeeper_c.c:543: obj_id: 3fd92ce3714c, read 1 bytes from the queue (0x7fb25a188c40)'s pipe
DEBUG 0x101662000:zookeeper_lib.c:302: zkrb_event_to_ruby ZKRB_WATCHER

DEBUG 0x101768000:zookeeper_lib.c:375: ZOOKEEPER_C_STATE WATCHER type = -1, state = 1, path = 0x7fb25a12acb0, value = 

DEBUG 0x101662000:zookeeper_c.c:543: obj_id: 3fd92ce3714c, read 1 bytes from the queue (0x7fb25a188c40)'s pipe
DEBUG 0x101662000:zookeeper_lib.c:302: zkrb_event_to_ruby ZKRB_WATCHER
```

**Comment by aia** [comment]
Figured it out.

@zkem.watcher.register_state_handler :connecting will actually be fired on zookeeper disconnects.

**Comment by slyphon** [comment]
oh, that's a bug though, lemme write a spec for it and fix

**Comment by slyphon** [comment]
have a look, let me know if you think this is good enough, or if there's a different change you'd suggest.

**Comment by aia** [comment]
Looks great!
Thank you for fixing this.

I am glad I learned more about troubleshooting the zookeeper client.

**Comment by slyphon** [comment]
awesome! i'm glad someone is using this code :D

**Comment by aia** [comment]
I opensourced my code that uses zk-eventmachine :)
https://github.com/aia/vpn-watch
It's work in progress, but I really like what I see.

You are maintaining the only usable Ruby Zookeeper gem!
Thank you for all the great work.

**Comment by slyphon** [comment]
Awesome! I'm glad it's useful to you! 

just so you know, I'm usually hanging out in #zk-gem on irc.freenode.net if you need help
